// src/components/WebSiteCard/index.tsx
/*
 * @Author: 白雾茫茫丶<baiwumm.com>
 * @Date: 2026-02-05 14:08:41
 * @LastEditors: 白雾茫茫丶<baiwumm.com>
 * @LastEditTime: 2026-03-09 15:42:42
 * @Description: 站点卡片
 */
"use client";
import { CircleInfo } from '@gravity-ui/icons';
import { Card, Chip, cn, Tooltip } from '@heroui/react';
import Image from 'next/image';
import { type CSSProperties, type FC, memo, useCallback } from 'react';

import { generateLogoUrl } from '@/lib/utils';

type WebsiteCardProps = {
  data: App.Website;
  handleClick: (id: string) => Promise<void>;
}

const WebsiteCard: FC<WebsiteCardProps> = memo(function WebsiteCard({ data, handleClick }) {
  const { id, name, desc, vpn, logo, tags, pinned, recommend, url, commonlyUsed, logoAccent } = data || {};

  const handleLinkPress = useCallback(() => {
    handleClick(id);
    window.open(url)
  }, [handleClick, id, url]);
  return (
    <Card
      className={cn("flex flex-col h-full relative overflow-hidden shadow-lg transition-transform duration-300 hover:-translate-y-1.5 animated-border animate-fade cursor-pointer after:border-[var(--logo-border-color)]")}
      onMouseEnter={(e) => {
        e.currentTarget.classList.add('hovered');
      }}
      style={{
        "--logo-border-color": logoAccent || "var(--accent)"
      } as CSSProperties}
      onClick={handleLinkPress}
    >
      <Card.Header>
        <Card.Title className="flex items-center gap-2">
          {logo ? (
            <Image src={generateLogoUrl(logo)} width={40} height={40} alt={name} />
          ) : null}
          <div className="flex flex-col gap-1">
            <div className="flex items-center gap-2">
              <div className="text-lg font-bold">{name}</div>
              {vpn ? (
                <Tooltip delay={0}>
                  <Tooltip.Trigger aria-label="VPN">
                    <CircleInfo className="text-muted" />
                  </Tooltip.Trigger>
                  <Tooltip.Content showArrow>
                    <Tooltip.Arrow />
                    访问需要开启 VPN 服务
                  </Tooltip.Content>
                </Tooltip>
              ) : null}
            </div>
            {tags?.length ? (
              <div className="flex flex-wrap gap-1">
                {tags.map(tag => (
                  <Chip key={tag} variant='soft' className="rounded-full text-[10px]/4">{tag}</Chip>
                ))}
              </div>
            ) : null}
          </div>
        </Card.Title>
        {desc ? (
          <Card.Description className="text-xs overflow-hidden line-clamp-2 wrap-break-word mt-1">{desc}</Card.Description>
        ) : null}
      </Card.Header>
      <div className="absolute right-2 top-2 flex gap-1">
        {/* 置顶标签 */}
        {pinned ? (
          <Chip color="success" variant='soft' className="rounded-full text-[10px]/4">置顶</Chip>
        ) : null}
        {/* 是否推荐 */}
        {recommend ? (
          <Chip color="warning" variant='soft' className="rounded-full text-[10px]/4">推荐</Chip>
        ) : null}
        {/* 是否常用 */}
        {commonlyUsed ? (
          <Chip variant='soft' className="rounded-full text-[10px]/4 text-blue-500 bg-blue-100 dark:bg-blue-200">常用</Chip>
        ) : null}
      </div>
    </Card>
  )
})
export default WebsiteCard;

// src/components/WebsiteCard/index.vue
<template>
  <div
    v-umami="{ name: websiteInfo.name, url: websiteInfo.url }"
    class="relative h-full cursor-pointer card-base animated-border animate-fade after:border-green-500/50 dark:after:border-green-400/50"
    shadow="hover"
    @click="handleClick"
    @mouseenter="$event.target?.classList.add('hovered')"
  >
    <div class="flex flex-col gap-3">
      <div class="flex gap-2 items-center">
        <SiteImage :url="websiteInfo.logo" :color="websiteInfo.color" />
        <div class="flex flex-col gap-0.5">
          <div class="flex gap-1 items-center">
            <div class="text-lg font-semibold">{{ websiteInfo.name }}</div>
            <template v-if="websiteInfo.vpn">
              <el-tooltip effect="dark" content="访问需要开启 VPN 服务" placement="bottom">
                <Icon name="ri:error-warning-line" class="text-slate-400" />
              </el-tooltip>
            </template>
          </div>
          <div class="flex gap-1 items-center text-xs text-slate-400 font-thin">
            <template v-for="(tag, index) in websiteInfo.tags" :key="index">
              <el-tag effect="light" type="success" size="small" round>{{ tag }}</el-tag>
            </template>
          </div>
        </div>
      </div>
      <div class="text-xs text-gray-500 dark:text-gray-400 line-clamp-2 leading-6">
        {{ websiteInfo.desc }}
      </div>
    </div>
    <div class="flex gap-1 absolute top-2 right-2">
      <!-- 置顶标签 -->
      <template v-if="websiteInfo.pinned">
        <el-tag type="success" effect="dark" size="small"> 置顶 </el-tag>
      </template>
      <!-- 是否推荐 -->
      <template v-if="websiteInfo.recommend">
        <el-tag type="info" effect="dark" size="small"> 推荐 </el-tag>
      </template>
    </div>
  </div>
</template>
<script setup lang="ts">
import type { WebsiteList } from '~/types'
// 父组件传递参数
const props = defineProps<{
  websiteInfo: WebsiteList
}>()

// 点击卡片回调
const handleClick = () => {
  window.open(props.websiteInfo.url)
}
</script>
<style lang="scss" scoped></style>
