// src/components/Header/index.tsx
/*
 * @Author: 白雾茫茫丶<baiwumm.com>
 * @Date: 2026-01-21 17:57:28
 * @LastEditors: 白雾茫茫丶<baiwumm.com>
 * @LastEditTime: 2026-07-06 18:16:53
 * @Description: 顶部导航
 */
"use client"
import { HouseFill, LogoGithub } from '@gravity-ui/icons';
import { Button, Tooltip } from '@heroui/react';
import Image from 'next/image';
import Link from "next/link";
import { type FC, type ReactNode } from 'react';

import { ShimmeringText } from '@/components/ShimmeringText';
import ThemeSwitcher from '@/components/ThemeSwitcher';
import TimeAndLunar from '@/components/TimeAndLunar';
import UserAvatar from '@/components/UserAvatar';
import pkg from '#/package.json';

type Social = {
  name: string;
  url: string;
  icon: ReactNode;
}

const socials: Social[] = [
  {
    name: "GitHub",
    url: pkg.git.url,
    icon: <LogoGithub />
  }
]

const Header: FC = () => {
  return (
    <header className="sticky top-0 p-4 z-20 backdrop-blur-sm container mx-auto flex justify-between items-center" id="header">
      {/* 左侧 Logo */}
      <Link href="/">
        <div className="flex gap-2 items-center justify-self-start">
          <div className="size-8 relative">
            <Image src="/logo.svg" fill alt="Logo" />
          </div>
          <ShimmeringText
            text={process.env.NEXT_PUBLIC_APP_NAME!}
            className="text-xl font-black"
            duration={1.5}
            repeatDelay={1}
            color="var(--accent)"
            shimmerColor="var(--accent-foreground)"
          />
        </div>
      </Link>
      <TimeAndLunar />
      {/* 右侧区域 */}
      <div className="flex items-center gap-2 justify-self-end">
        <ThemeSwitcher />
        {socials.map(({ name, url, icon }) => (
          <Tooltip key={name} delay={0}>
            <Link href={url} aria-label={name} target="_blank">
              <Button variant="ghost" isIconOnly size='sm'>
                {icon}
              </Button>
            </Link>
            <Tooltip.Content showArrow>
              <Tooltip.Arrow />
              {name}
            </Tooltip.Content>
          </Tooltip>
        ))}
        <Tooltip>
          <Link href={pkg.author.url} aria-label="主页" target="_blank">
            <Button variant="ghost" isIconOnly size='sm'>
              <HouseFill />
            </Button>
          </Link>
          <Tooltip.Content showArrow>
            <Tooltip.Arrow />
            个人主页
          </Tooltip.Content>
        </Tooltip>
        {/* 登录用户信息 */}
        <UserAvatar />
      </div>
    </header >
  )
}
export default Header;

// src/components/Header/index.vue
<!--
 * @Author: 白雾茫茫丶<baiwumm.com>
 * @Date: 2024-04-10 16:25:21
 * @LastEditors: 白雾茫茫丶<baiwumm.com>
 * @LastEditTime: 2024-05-31 09:12:23
 * @Description: 顶部布局
-->
<template>
  <el-header
    class="flex gap-4 justify-between items-center sticky top-0 h-14 shadow-md dark:shadow-white-500/50 backdrop-blur transition-all w-full dark:shadow-[0_4px_6px_-1px_rgb(255,255,255,0.1)]"
  >
    <!-- logo -->
    <a
      href="/"
      class="flex gap-4 items-center"
    >
      <!-- logo -->
      <NuxtImg
        src="/logo.svg"
        alt="logo"
        class="w-8 h-8"
      />
      <ColorModeSvg
        light-fill="#000"
        dark-fill="#fff"
        name="dream-site"
        class-name="h-6"
      />
    </a>
    <!-- 右侧 社交图标 -->
    <div class="flex">
      <!-- 夜间模式 -->
      <ColorMode />
      <!-- github -->
      <SocialIcon
        url="https://github.com/baiwumm/dream-site"
        tip="Github"
        icon="i-simple-icons-github"
      />
    </div>
  </el-header>
</template>
