// src/components/UserAvatar/index.tsx
/*
 * @Author: 白雾茫茫丶<baiwumm.com>
 * @Date: 2026-01-22 15:44:57
 * @LastEditors: 白雾茫茫丶<baiwumm.com>
 * @LastEditTime: 2026-08-03 16:50:55
 * @Description: 用户头像
 */
import { useRouter } from '@bprogress/next/app'
import { Person } from '@gravity-ui/icons'
import { Button, Spinner, Tooltip } from '@heroui/react'

import UserMenu from '@/components/UserMenu'
import { useSupabaseUser } from '@/hooks/use-supabase-user'

import type { FC } from 'react'

const UserAvatar: FC = () => {
  const router = useRouter()
  // 获取登录用户信息
  const { user, loading } = useSupabaseUser()

  return loading
    ? (
        <Spinner size="sm" />
      )
    : user
      ? (
          <UserMenu user={user} />
        )
      : (
          <Tooltip>
            <Button size="sm" variant="ghost" isIconOnly onClick={() => router.push('/login')}>
              <Person />
            </Button>
            <Tooltip.Content showArrow>
              <Tooltip.Arrow />
              登录
            </Tooltip.Content>
          </Tooltip>
        )
}
export default UserAvatar

// src/components/UserAvatar/index.vue
<!--
 * @Author: 白雾茫茫丶<baiwumm.com>
 * @Date: 2024-06-06 17:53:32
 * @LastEditors: 白雾茫茫丶<baiwumm.com>
 * @LastEditTime: 2024-06-11 09:22:58
 * @Description: 当前登录用户头像
-->
<template>
  <client-only>
    <template v-if="user">
      <el-button circle text>
        <el-avatar :src="user.user_metadata.avatar_url" :size="20" />
      </el-button>
    </template>
    <template v-else>
      <el-tooltip content="登录">
        <NuxtLink to="/login">
          <el-button circle text>
            <Icon name="ri:user-3-line" class="h-5 w-5" />
          </el-button>
        </NuxtLink>
      </el-tooltip>
    </template>
  </client-only>
</template>
<script setup lang="ts">
const user = useSupabaseUser()
</script>
